name: Languages Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-languages.svg
          user: Sadikn7i
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_threshold: 0%
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: Jupyter Notebook
