name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # Use GitHub token (no need for METRICS_TOKEN)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Basic config
          user: Sadikn7i
          template: classic
          base: header, activity, community
          config_timezone: Asia/Tokyo
          
          # Isometric calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Languages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_indepth: no
          
          # Lines of code
          plugin_lines: yes
          plugin_lines_sections: repositories
          plugin_lines_repositories_limit: 4

