name: Lines Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  lines:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics-lines.svg
          user: Sadikn7i
          template: classic
          base: ""
          config_timezone: Asia/Tokyo
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_sections: repositories
          plugin_lines_repositories_limit: 4
