name: GitHub Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: Sadikn7i
          base: ""
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_ignored: >-
            jupyter notebook
          plugin_languages_limit: 8
          plugin_languages_layout: compact
          template: classic
          
          # This line has been updated for Japan
          config_timezone: Asia/Tokyo
